### ISSUE TITLE
Error running RW in Docker

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo-testing#110]
This error occurs when running any module in rwalk running within docker:
```
java.lang.RuntimeException: Failed to connect to zookeeper (localhost:2181) within 2x zookeeper timeout period 30000
	at org.apache.accumulo.fate.zookeeper.ZooSession.connect(ZooSession.java:157)
	at org.apache.accumulo.fate.zookeeper.ZooSession.getSession(ZooSession.java:201)
	at org.apache.accumulo.fate.zookeeper.ZooReader.getSession(ZooReader.java:42)
	at org.apache.accumulo.fate.zookeeper.ZooReader.getZooKeeper(ZooReader.java:46)
	at org.apache.accumulo.fate.zookeeper.ZooCache.getZooKeeper(ZooCache.java:148)
	at org.apache.accumulo.fate.zookeeper.ZooCache.access$900(ZooCache.java:48)
	at org.apache.accumulo.fate.zookeeper.ZooCache$2.run(ZooCache.java:406)
	at org.apache.accumulo.fate.zookeeper.ZooCache$2.run(ZooCache.java:379)
	at org.apache.accumulo.fate.zookeeper.ZooCache$ZooRunnable.retry(ZooCache.java:271)
	at org.apache.accumulo.fate.zookeeper.ZooCache.get(ZooCache.java:434)
	at org.apache.accumulo.fate.zookeeper.ZooCache.get(ZooCache.java:364)
	at org.apache.accumulo.core.clientImpl.ClientContext.getInstanceID(ClientContext.java:398)
	at org.apache.accumulo.core.clientImpl.Tables.getTableMap(Tables.java:179)
	at org.apache.accumulo.core.clientImpl.Tables.getTableMap(Tables.java:167)
	at org.apache.accumulo.core.clientImpl.Tables.getNameToIdMap(Tables.java:151)
	at org.apache.accumulo.core.clientImpl.TableOperationsImpl.exists(TableOperationsImpl.java:192)
	at org.apache.accumulo.testing.randomwalk.bulk.Setup.visit(Setup.java:49)
	at org.apache.accumulo.testing.randomwalk.Module.visit(Module.java:237)
	at org.apache.accumulo.testing.randomwalk.Framework.run(Framework.java:48)
	at org.apache.accumulo.testing.randomwalk.Framework.main(Framework.java:92)
```

**Comment by milleruntime** [comment]
I was missing the ```--network="host" ``` option when running the docker container.
