### ISSUE TITLE
Could not run continuous ingest

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo-testing#16]
I was unable to run continuous ingest for 1.9.2RC1 because of the following problem.  I was using hadoop 2.8.4.

```
java.lang.NoSuchMethodError: org.apache.hadoop.hdfs.HAUtil.isLogicalUri(Lorg/apache/hadoop/conf/Configuration;Ljava/net/URI;)Z
	at org.apache.twill.filesystem.FileContextLocation.toURI(FileContextLocation.java:149)
	at org.apache.twill.yarn.YarnTwillPreparer.createLocalFile(YarnTwillPreparer.java:446)
	at org.apache.twill.yarn.YarnTwillPreparer.createLocalFile(YarnTwillPreparer.java:442)
	at org.apache.twill.yarn.YarnTwillPreparer.createAppMasterJar(YarnTwillPreparer.java:468)
	at org.apache.twill.yarn.YarnTwillPreparer.access$100(YarnTwillPreparer.java:111)
	at org.apache.twill.yarn.YarnTwillPreparer$1.call(YarnTwillPreparer.java:338)
	at org.apache.twill.yarn.YarnTwillPreparer$1.call(YarnTwillPreparer.java:329)
	at org.apache.twill.yarn.YarnTwillController.doStartUp(YarnTwillController.java:97)
	at org.apache.twill.internal.AbstractZKServiceController.startUp(AbstractZKServiceController.java:75)
	at org.apache.twill.internal.AbstractExecutionServiceController$ServiceDelegate.startUp(AbstractExecutionServiceController.java:175)
	at com.google.common.util.concurrent.AbstractIdleService$1$1.run(AbstractIdleService.java:43)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by keith-turner** [comment]
That class is annotated as Private by Hadoop, so Twill should not be using it.

https://hadoop.apache.org/docs/current/hadoop-yarn/hadoop-yarn-api/apidocs/org/apache/hadoop/yarn/conf/HAUtil.html
