### ISSUE TITLE
CopyTable thread died during Randomwalk MultiTable test run

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo-testing#196]
I was running 4 threads for the MultiTable randomwalk test locally on my machine using Uno. I had 2 tservers running. After some time, one of the threads died while trying to do copyTable. Typically, I see this error when I kill the test myself. But this time the tserver reported the error on its own. 
<pre>
Caused by: java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:?]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:?]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[?:?]
        at sun.nio.ch.IOUtil.read(IOUtil.java:245) ~[?:?]
        at sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:356) ~[?:?]
        at org.apache.thrift.transport.TNonblockingSocket.read(TNonblockingSocket.java:149) ~[libthrift-0.15.0.jar:0.15.0]
        ... 5 more
</pre>

From the MultiTable walker thread:
<pre>
2022-03-15T08:47:12,162 [randomwalk.multitable.CopyTable] DEBUG: copying multi_ip_10_113_12_25_13 to multi_ip_10_113_12_25_17
2022-03-15T08:52:12,132 [testing.randomwalk.Module] WARN : Node org.apache.accumulo.testing.randomwalk.multitable.CopyTable has been running for 300.022 seconds. You may want to look into it.
</pre>

I am not sure what happened but the Hadoop MR job is still running.

**Comment by milleruntime** [comment]
The copy just took a while. I guess I am just too impatient :grin: 
<pre>
SUCCEEDED
--
Tue Mar 15 08:47:16 -0400 2022
Tue Mar 15 08:47:16 -0400 2022
Tue Mar 15 09:26:53 -0400 2022
39mins, 36sec
</pre>
