### ISSUE TITLE
IllegalArgumentException: Rwalk Simpl.xml and Basic.xml module

### ISSUE THREAD

**Issue by Manno15** [apache/accumulo-testing#213]
While testing some possible jar issues, I ran into an IlegalArgumentException while trying to run the `Simple.xml` module of rwalk. Stacktrace below: 

<details>

```
java.lang.IllegalArgumentException: InputStream cannot be null
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:118) ~[?:?]
	at org.apache.accumulo.testing.randomwalk.Module.loadFromXml(Module.java:521) ~[accumulo-testing-shaded.jar:?]
	at org.apache.accumulo.testing.randomwalk.Module.<init>(Module.java:194) ~[accumulo-testing-shaded.jar:?]
	at org.apache.accumulo.testing.randomwalk.Framework.getNode(Framework.java:79) ~[accumulo-testing-shaded.jar:?]
	at org.apache.accumulo.testing.randomwalk.Framework.run(Framework.java:53) ~[accumulo-testing-shaded.jar:?]
	at org.apache.accumulo.testing.randomwalk.Framework.main(Framework.java:98) ~[accumulo-testing-shaded.jar:?]
2022-08-07T12:57:31,481 [testing.randomwalk.Framework] ERROR: Error during random walk
java.lang.Exception: Failed to parse xml at randomwalk/modules/Simple.xml
	at org.apache.accumulo.testing.randomwalk.Module.loadFromXml(Module.java:524) ~[accumulo-testing-shaded.jar:?]
	at org.apache.accumulo.testing.randomwalk.Module.<init>(Module.java:194) ~[accumulo-testing-shaded.jar:?]
	at org.apache.accumulo.testing.randomwalk.Framework.getNode(Framework.java:79) ~[accumulo-testing-shaded.jar:?]
	at org.apache.accumulo.testing.randomwalk.Framework.run(Framework.java:53) ~[accumulo-testing-shaded.jar:?]
	at org.apache.accumulo.testing.randomwalk.Framework.main(Framework.java:98) ~[accumulo-testing-shaded.jar:?]
2022-08-07T12:57:31,481 [testing.randomwalk.Framework] INFO : Test finished

```

</details>

I am currently still investigating but creating the issue in case someone wants to take a stab at it. 

Current commit: https://github.com/apache/accumulo-testing/commit/ea659deaeacb46a4b22d4844f52e92b9508302fb 
and using latest accumlo-2.1 (though seems unrelated).

**Comment by Manno15** [comment]
Seems this issue is rather simple. Running just `./bin/rwalk Simple.xml` looks for the modeul inside `randomwalk/modules/` whereas it is actually located inside `randomwalk/modules/unit/`. This also holds true for the `Basic.xml` module.

**Comment by Manno15** [comment]
Below is the code snippet that looks for the module that the user specified to be run.

https://github.com/apache/accumulo-testing/blob/da4a4343d738f4861d7109290d3618f0a09c93b8/src/main/java/org/apache/accumulo/testing/randomwalk/Module.java#L519-L524

**Comment by DomGarguilo** [comment]
I'm not certain of the intentions behind these files in the `unit` directory (`Basic` and `Simple`), but it doesn't seem to me that these are necessarily supposed to be run on their own by the user. Instead they seem like components of the other randomwalk modules/tests.

**Comment by Manno15** [comment]
Yes, but they still show up as options for the user to choose if you enter the rwalk command without any module.

**Comment by DomGarguilo** [comment]
> Yes, but they still show up as options for the user to choose if you enter the rwalk command without any module.

Oh yea good point. I didn't see that until now. Maybe in that list those two can be prefixed with `/unit`
