### ISSUE TITLE
RW Concurrent test errors on BulkImport for 2.0

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo-testing#83]
I am testing the 2.0 branch at commit 9e32263e7 using Uno and keep seeing this same error while trying to run RW Concurrent module:
```
2019-06-20 14:29:52,354 [testing.randomwalk.Framework] INFO : Running random walk test with module: Concurrent.xml
2019-06-20 14:30:19,161 [testing.randomwalk.Framework] ERROR: Error during random walk
java.lang.Exception: Error running node ct.BulkImport
	at org.apache.accumulo.testing.randomwalk.Module.visit(Module.java:370)
	at org.apache.accumulo.testing.randomwalk.Framework.run(Framework.java:48)
	at org.apache.accumulo.testing.randomwalk.Framework.main(Framework.java:92)
Caused by: org.apache.accumulo.core.client.AccumuloException: Bulk import  directory /tmp/concurrent_bulk/b_4640b9365aa878f3 does not exist!
	at org.apache.accumulo.core.clientImpl.TableOperationsImpl.checkPath(TableOperationsImpl.java:1173)
	at org.apache.accumulo.core.clientImpl.TableOperationsImpl.importDirectory(TableOperationsImpl.java:1197)
	at org.apache.accumulo.testing.randomwalk.concurrent.BulkImport.visit(BulkImport.java:134)
	at org.apache.accumulo.testing.randomwalk.Module$1.call(Module.java:303)
	at org.apache.accumulo.testing.randomwalk.Module$1.call(Module.java:298)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.accumulo.fate.util.LoggingRunnable.run(LoggingRunnable.java:35)
	at java.lang.Thread.run(Thread.java:748)
2019-06-20 14:30:19,163 [testing.randomwalk.Framework] INFO : Test finished
```

The BulkImport module is currently using the old deprecated importDirectory but it should still work.

**Comment by milleruntime** [comment]
Output from running rfile-info on one of the files:
```
Reading file: hdfs://localhost:8020/tmp/concurrent_bulk/b_10ba9b66110a1e44/file01.rf
2019-06-25 16:00:35,678 [rfile.PrintInfo] ERROR: Error reading crypto params
java.io.EOFException: Cannot seek after EOF
	at org.apache.hadoop.hdfs.DFSInputStream.seek(DFSInputStream.java:1440)
	at org.apache.hadoop.fs.FSDataInputStream.seek(FSDataInputStream.java:65)
	at org.apache.accumulo.core.file.rfile.PrintInfo.printCryptoParams(PrintInfo.java:280)
	at org.apache.accumulo.core.file.rfile.PrintInfo.execute(PrintInfo.java:179)
	at org.apache.accumulo.start.Main.lambda$execKeyword$0(Main.java:129)
	at java.lang.Thread.run(Thread.java:748)
2019-06-25 16:00:35,695 [start.Main] ERROR: Thread 'rfile-info' died.
java.io.IOException: Not a valid BCFile.
	at org.apache.accumulo.core.file.rfile.bcfile.BCFile$Magic.readAndVerify(BCFile.java:912)
	at org.apache.accumulo.core.file.rfile.bcfile.BCFile$Reader.<init>(BCFile.java:607)
	at org.apache.accumulo.core.file.blockfile.impl.CachableBlockFile$Reader.getBCFile(CachableBlockFile.java:176)
	at org.apache.accumulo.core.file.blockfile.impl.CachableBlockFile$Reader.getMetaBlock(CachableBlockFile.java:400)
	at org.apache.accumulo.core.file.rfile.RFile$Reader.<init>(RFile.java:1156)
	at org.apache.accumulo.core.file.rfile.RFile$Reader.<init>(RFile.java:1251)
	at org.apache.accumulo.core.file.rfile.PrintInfo.execute(PrintInfo.java:183)
	at org.apache.accumulo.start.Main.lambda$execKeyword$0(Main.java:129)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by milleruntime** [comment]
This must be some race condition with this Test.  If I comment out the importDirectory and stop the test from deleteing the files, they all look fine.  I was even able to bulk import the same files manually using the shell.
